# Catalog properties
catalog_name: "Toy Catalog"

# Styling
logo_path: "/home/jovyan/tutorials/notebooks/catalog_tutorials/test_data/datalad_logo_funky.svg" # path to logo
link_color: "#32A287" # hex color code
link_hover_color: "#A9FDAC" # hex color code

# Handling multiple metadata sources
property_source:
  dataset: {}